# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9184f5af891dda3c2197968c047e52d14ee1821207abf6b060d17b583964613669a78cb9601191a8b3930bf12aa584d025787c41a0cd4b2e9a0ea502ab459089

test:
  secret_key_base: 05148083d62b5306d1becb58215ae448c27314a8c63de73cfba6c916b05adb2c289c5070535819acc571fae02d074ac6710e7d33e84057b50d0d3129233cd00a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
